modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="MIT License"
[[mods]]
modId="custombonuschest" #mandatory
version="MC1.16.5_1.0" #mandatory
displayName="CustomBonusChest" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="djmanly" #optional
description='Mod that allows customization of the Bonus Chest loot.'
[[dependencies.custombonuschest]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
